### ISSUE TITLE
Summoning earth elemental, fire elemental by spell crashes client on SphereServer.

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#296]
![ekran goruntusu 5](https://cloud.githubusercontent.com/assets/11157985/9370207/28d9f3f0-46d7-11e5-85c1-a021d6407ace.png)
Adding them does not crash client.

**Comment by ZaneDubya** [comment]
Hmmmmmmm... I'll have to take a look at this. Thank you for reporting!

**Comment by ZaneDubya** [comment]
@robertdeclaux I think I may have fixed this issue. Give it another try?

**Comment by ZaneDubya** [comment]
@robertdeclaux  When you post a screen shot, could you include the 'locals' window? That will show me the values of all the variables in the local context of the error, which would be helpful!

**Comment by robertdeclaux** [comment]
I will do it as soon as i can.

**Comment by robertdeclaux** [comment]
Not sure if it's what you want
![ekran goruntusu 9](https://cloud.githubusercontent.com/assets/11157985/9568272/29c8ceb6-4f4d-11e5-827d-d9462ec6646d.png)

**Comment by ZaneDubya** [comment]
@robertdeclaux I think I've fixed it (again). But there is something funky going on with how Sphere sets up layers for elementals. Try it again?

**Comment by robertdeclaux** [comment]
After summoning them it was always crashing when i trying to login again until they disappear, This case and summoning air elemental fixed completely but summoning fire elemental still crashes.(But i can login after crash and see the fire elemental)
![ekran goruntusu 10](https://cloud.githubusercontent.com/assets/11157985/9641776/1913c258-51c1-11e5-839e-86739f26c331.png)

**Comment by ZaneDubya** [comment]
Heck, I have no idea what's going on. Mind if I jump on your server this weekend?

**Comment by robertdeclaux** [comment]
Just let me now when you are free
2 Eyl 2015 22:48 tarihinde "Zane Wagner" notifications@github.com yazdı:

**Comment by ZaneDubya** [comment]
Elementals are fixed in commit 7270c571f5. There is a problem with daemons that is related to how I'm reading (mis-reading) bodyconv.def.

**Comment by ZaneDubya** [comment]
I've fixed daemons! Residual issue with dragon chest pieces (possibly other) equipment not showing up...

**Comment by ZaneDubya** [comment]
Fixed the body.def file reader. Closing as fixed.
